### PR TITLE
Leaderboard: final touches

### PR DESCRIPTION
**Pull request by Danny-imo**
**In this milestone**

- Improve the look and feel of the application, adding the styles of my choice

- use plain CSS for styling

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @Danny-imo , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- App styled like provided wireframe.

## Required Changes ♻️
_Check the comments under the review._

- [ ] As per the project requirements, you should mention in the README, the API you are consuming. Kindly do so before submitting for a re-review. ⬇️
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] When posting a score, the scoreboard should not update automatically. Instead, it should only refresh and show the latest score only after hitting the refresh button. Since, this requirement was not of this milestone, I am marking this as optional. However, to improve the feel of your app, you can consider implementing it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
@Danny-imo, please push the changes required by the previous developer.

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @Danny-imo, 

 You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* Leaderboard looking great. ✔️ 

 ## Required Changes ♻️
- Hello, thank you for submitting your project again. I noticed that you did not make any changes to your README file as suggested by the previous reviewer. It is important to follow the project requirements and the feedback given by the reviewers, as they are meant to help you improve your skills and showcase your work. Please add a section in your README file that mentions the API you are using. This will make your project more informative and professional. You can find some examples of how to write a good README file here and here. I hope this helps. Please make the necessary changes and resubmit your project for another review. Good luck! 😊
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- For future pull requests, please notice that your branch name `Leaderboard-final` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-Leaderboard-final`. This makes it easier to track the changes and the purpose of each branch.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by topeogunleye — APPROVED** [review]
### Hi @Danny-imo, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
congratulations
>
## To highlight :champagne: 
- Added information about the API you're using ✔️ 
 
## [Optional] suggestions:
- For future pull requests, please notice that your branch name `Leaderboard-final` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-Leaderboard-final`. This makes it easier to track the changes and the purpose of each branch. 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
